# Generated by Django 4.0.3 on 2022-04-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
